export const FETCH_ACCOUNT_REQUEST = 'FETCH_ACCOUNT_REQUEST';
export const FETCH_ACCOUNT_SUCCESS = 'FETCH_ACCOUNT_SUCCESS';
export const FETCH_ACCOUNT_FAIL = 'FETCH_ACCOUNT_FAIL';
export const ADD_USER_OBJECT = 'ADD_USER_OBJECT';
export const DELETE_USER_OBJECT = 'DELETE_USER_OBJECT';
export const UPDATE_USER_OBJECT = 'UPDATE_USER_OBJECT';