export const FETCH_CMT_REQUEST = 'FETCH_CMT_REQUEST';
export const FETCH_CMT_SUCCESS = 'FETCH_CMT_SUCCESS';
export const FETCH_CMT_FAIL = 'FETCH_CMT_FAIL';
export const ADD_CMT_OBJECT = 'ADD_CMT_OBJECT';
export const DELETE_CMT_OBJECT = 'DELETE_CMT_OBJECT';
export const UPDATE_CMT_OBJECT = 'UPDATE_CMT_OBJECT';