export const FETCH_COLORS_REQUEST = 'FETCH_COLORS_REQUEST';
export const FETCH_COLORS_SUCCESS = 'FETCH_COLORS_SUCCESS';
export const FETCH_COLORS_FAIL = 'FETCH_COLORS_FAIL';
export const ADD_COLORS_OBJECT = 'ADD_COLORS_OBJECT';
export const DELETE_COLORS_OBJECT = 'DELETE_COLORS_OBJECT';
export const UPDATE_COLORS_OBJECT = 'UPDATE_COLORS_OBJECT';