export const FETCH_MAIN_REQUEST = 'FETCH_MAIN_REQUEST';
export const FETCH_MAIN_SUCCESS = 'FETCH_MAIN_SUCCESS';
export const FETCH_MAIN_FAIL = 'FETCH_MAIN_FAIL';
export const ADD_MAIN_OBJECT = 'ADD_MAIN_OBJECT';
export const DELETE_MAIN_OBJECT = 'DELETE_MAIN_OBJECT';
export const UPDATE_MAIN_OBJECT = 'UPDATE_MAIN_OBJECT';