export const FETCH_MENUS_REQUEST = 'FETCH_MENUS_REQUEST';
export const FETCH_MENUS_SUCCESS = 'FETCH_MENUS_SUCCESS';
export const FETCH_MENUS_FAIL = 'FETCH_MENUS_FAIL';
export const ADD_MENUS_OBJECT = 'ADD_MENUS_OBJECT';
export const DELETE_MENUS_OBJECT = 'DELETE_MENUS_OBJECT';
export const UPDATE_MENUS_OBJECT = 'UPDATE_MENUS_OBJECT';