export const FETCH_ORDER_REQUEST = 'FETCH_ORDER_REQUEST';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';
export const DELETE_ORDER_OBJECT = 'DELETE_ORDER_OBJECT';
export const ADD_ORDER_OBJECT = 'ADD_ORDER_OBJECT';
export const UPDATE_ORDER_OBJECT = 'UPDATE_ORDER_OBJECT';