export const FETCH_PAGE_REQUEST = 'FETCH_PAGE_REQUEST';
export const FETCH_PAGE_SUCCESS = 'FETCH_PAGE_SUCCESS';
export const FETCH_PAGE_FAIL = 'FETCH_PAGE_FAIL';
export const ADD_PAGE_OBJECT = 'ADD_PAGE_OBJECT';
export const DELETE_PAGE_OBJECT = 'DELETE_PAGE_OBJECT';
export const UPDATE_PAGE_OBJECT = 'UPDATE_PAGE_OBJECT';