export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';
export const DELETE_PRODUCT_OBJECT = 'DELETE_PRODUCT_OBJECT';
export const UPDATE_PRODUCT_OBJECT = 'UPDATE_PRODUCT_OBJECT';
export const ADD_PRODUCT_OBJECT = 'ADD_PRODUCT_OBJECT';
export const UPDATE_IMGs_PRODUCT_OBJECT = 'UPDATE_IMGs_PRODUCT_OBJECT';