export const FETCH_PROMOTIONS_REQUEST = 'FETCH_PROMOTIONS_REQUEST';
export const FETCH_PROMOTIONS_SUCCESS = 'FETCH_PROMOTIONS_SUCCESS';
export const FETCH_PROMOTIONS_FAIL = 'FETCH_PROMOTIONS_FAIL';
export const ADD_PROMOTIONS_OBJECT = 'ADD_PROMOTIONS_OBJECT';
export const DELETE_PROMOTIONS_OBJECT = 'DELETE_PROMOTIONS_OBJECT';
export const UPDATE_PROMOTIONS_OBJECT = 'UPDATE_PROMOTIONS_OBJECT';