export const FETCH_SKUS_REQUEST = 'FETCH_SKUS_REQUEST';
export const FETCH_SKUS_SUCCESS = 'FETCH_SKUS_SUCCESS';
export const FETCH_SKUS_FAIL = 'FETCH_SKUS_FAIL';
export const ADD_SKUS_OBJECT = 'ADD_SKUS_OBJECT';
export const DELETE_SKUS_OBJECT = 'DELETE_SKUS_OBJECT';
export const UPDATE_SKUS_OBJECT = 'UPDATE_SKUS_OBJECT';