export const FETCH_SLIDE_IMG_REQUEST = 'FETCH_SLIDE_IMG_REQUEST';
export const FETCH_SLIDE_IMG_SUCCESS = 'FETCH_SLIDE_IMG_SUCCESS';
export const FETCH_SLIDE_IMG_FAIL = 'FETCH_SLIDE_IMG_FAIL';
export const ADD_SLIDE_OBJECT = 'ADD_SLIDE_OBJECT';
export const DELETE_SLIDE_OBJECT = 'DELETE_SLIDE_OBJECT';
export const UPDATE_SLIDE_OBJECT = 'UPDATE_SLIDE_OBJECT';