export const FETCH_VIDEOS_REQUEST = 'FETCH_VIDEOS_REQUEST';
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
export const FETCH_VIDEOS_FAIL = 'FETCH_VIDEOS_FAIL';
export const ADD_VIDEOS_OBJECT = 'ADD_VIDEOS_OBJECT';
export const DELETE_VIDEOS_OBJECT = 'DELETE_VIDEOS_OBJECT';
export const UPDATE_VIDEOS_OBJECT = 'UPDATE_VIDEOS_OBJECT';