export const FETCH_WARANTYS_REQUEST = 'FETCH_WARANTYS_REQUEST';
export const FETCH_WARANTYS_SUCCESS = 'FETCH_WARANTYS_SUCCESS';
export const FETCH_WARANTYS_FAIL = 'FETCH_WARANTYS_FAIL';
export const ADD_WARANTYS_OBJECT = 'ADD_WARANTYS_OBJECT';
export const DELETE_WARANTYS_OBJECT = 'DELETE_WARANTYS_OBJECT';
export const UPDATE_WARANTYS_OBJECT = 'UPDATE_WARANTYS_OBJECT';