import Head from 'next/head'
import { useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import Header from '../components/Header'
import Footer from '../components/Footer'
import { getMain } from './../store/actions/main'

export default function Home() {
  const dispatch = useDispatch()
  const mainData = useSelector(state => state.main.data)

  useEffect(() => {
    dispatch(getMain())
  }, [])
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header headerData={mainData} />
      <div className='tel'>
        <a href={`tel:${mainData.phone}`} className='tel-call'>
          <i className='fa fa-phone' aria-hidden='true'></i>
        </a>
      </div>
      <Footer footerData={mainData} />
    </div>
  )
}
