import Head from 'next/head'
import { useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import Footer from '../components/Footer'
import styles from '../styles/Home.module.css'
// import './../assets/scss/common.scss'
// import './../assets/css/footer.scss'
// import './../assets/css/header.scss'
// import './../assets/css/variables.scss'
import { getMain } from './../store/actions/main'

export default function Home() {
  const dispatch = useDispatch()
  const mainData = useSelector(state => state.main.data)

  useEffect(() => {
    dispatch(getMain())
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>
      </main>

      <Footer footerData={mainData} />
    </div>
  )
}
